CC=gcc -Wall -g

exe = programa1 programa2 programa3 programa4 programa5 programa6 programa7 programa8 programa9 programa10 programa11 programa12 programa13 programa14 programa15 programa16 programa17 programa18

all: $(exe)


.PHONY : clean
clean :
	rm -f *.o
	rm -f *.out

programa1: programa1.o
	$(CC) -o programa1 programa1.o

programa2: programa2.o
	$(CC) -o programa2 programa2.o

programa3: programa3.o
	$(CC) -o programa3 programa3.o

programa4: programa4.o
	$(CC) -o programa4 programa4.o

programa5: programa5.o
	$(CC) -o programa5 programa5.o

programa6: programa6.o
	$(CC) -o programa6 programa6.o

programa7: programa7.o
	$(CC) -o programa7 programa7.o

programa8: programa8.o
	$(CC) -o programa8 programa8.o

programa9: programa9.o
	$(CC) -o programa9 programa9.o

programa10: programa10.o
	$(CC) -o programa10 programa10.o

programa11: programa11.o
	$(CC) -o programa11 programa11.o

programa12: programa12.o
	$(CC) -o programa12 programa12.o

programa13: programa13.o
	$(CC) -o programa13 programa13.o

programa14: programa14.o
	$(CC) -o programa14 programa14.o

programa15: programa15.o
	$(CC) -o programa15 programa15.o

programa16: programa16.o
	$(CC) -o programa16 programa16.o

programa17: programa17.o
	$(CC) -o programa17 programa17.o

programa18: programa18.o utilidades.o
	$(CC) -o programa18 programa18.o utilidades.o

programa1.o: programa1.c
	$(CC) -c programa1.c

programa2.o: programa2.c
	$(CC) -c programa2.c

programa3.o: programa3.c
	$(CC) -c programa3.c

programa4.o: programa4.c
	$(CC) -c programa4.c

programa5.o: programa5.c
	$(CC) -c programa5.c

programa6.o: programa6.c
	$(CC) -c programa6.c

programa7.o: programa7.c
	$(CC) -c programa7.c

programa8.o: programa8.c
	$(CC) -c programa8.c

programa9.o: programa9.c
	$(CC) -c programa9.c

programa10.o: programa10.c
	$(CC) -c programa10.c

programa11.o: programa11.c
	$(CC) -c programa11.c

programa12.o: programa12.c
	$(CC) -c programa12.c

programa13.o: programa13.c
	$(CC) -c programa13.c

programa14.o: programa14.c
	$(CC) -c programa14.c

programa15.o: programa15.c
	$(CC) -c programa15.c

programa16.o: programa16.c
	$(CC) -c programa16.c

programa17.o: programa17.c
	$(CC) -c programa17.c

programa18.o: programa18.c utilidades.c 
	$(CC) -c programa18.c

utilidades.o: utilidades.c
	$(CC) -c utilidades.c
